---
title: "ex2"
author: "Asier Ràfales Vila"
date: "29/5/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#---------------------------------------------------------------------------------------------
###FOLDER DESTINATION DEFINITIONS
#---------------------------------------------------------------------------------------------
workingDir <-getwd()
workingDir
dataDir <- file.path(workingDir, "GSE64896_RAW")
dataDir
resultsDir <- file.path(workingDir, "results")
resultsDir
setwd(resultsDir)
```




```{r eval=FALSE, include=FALSE}
# DO NOT RUN 
if (!require(GEOquery)) {
  source("http://bioconductor.org/biocLite.R")
  biocLite("GEOquery")
}

```


#
## INSTALLATION OF PACKAGES NEEDED
#

```{r eval=FALSE, include=FALSE}
source("http://bioconductor.org/biocLite.R")
biocLite("GEOquery")
```

```{r eval=FALSE, include=FALSE}
installifnot("pd.mogene.1.0.st.v1")
installifnot("mogene10sttranscriptcluster.db")
installifnot("oligo")
installifnot("limma")
installifnot("Biobase")
installifnot("arrayQualityMetrics")
installifnot("genefilter")
installifnot("multtest")
installifnot("annotate")
installifnot("xtable")
installifnot("gplots")
installifnot("scatterplot3d")
```




```{r}
targets <- read.delim("~/Documentos/uni/2n/3r_trimestre/omics techniques/2nd_part/Rafales_Asier_OmicsTechniques/Exercise_2/targets.txt")
targets
```


```{r}
CELfiles <- list.celfiles(file.path(dataDir))
CELfiles
```



```{r}
rawData <- read.celfiles(file.path(dataDir,CELfiles))
```


```{r}
#DEFINE SOME VARIABLES FOR PLOTS
sampleNames <- as.character(targets$Sample_name)
sampleNames
sampleColor <- as.character(targets$colors)
sampleColor


```

#---------------------------------------------------------------------------------------------
###QUALITY CONTROL OF ARRAYS: RAW DATA
#---------------------------------------------------------------------------------------------

```{r}

#BOXPLOT
boxplot(rawData, which="all",las=2, main="Intensity distribution of RAW data", 
        cex.axis=0.6, col=sampleColor, names=sampleNames)

```


```{r}
#HIERARQUICAL CLUSTERING
clust.euclid.average <- hclust(dist(t(exprs(rawData))),method="average")
plot(clust.euclid.average, labels=sampleNames, main="Hierarchical clustering of RawData", 
     cex=0.7,  hang=-1)
```




#PRINCIPAL COMPONENT ANALYSIS
```{r}
plotPCA <- function ( X, labels=NULL, colors=NULL, dataDesc="", scale=FALSE, formapunts=NULL, myCex=0.8,...)
{
  pcX<-prcomp(t(X), scale=scale) # o prcomp(t(X))
  loads<- round(pcX$sdev^2/sum(pcX$sdev^2)*100,1)
  xlab<-c(paste("PC1",loads[1],"%"))
  ylab<-c(paste("PC2",loads[2],"%"))
  if (is.null(colors)) colors=1
  plot(pcX$x[,1:2],xlab=xlab,ylab=ylab, col=colors, pch=formapunts, 
       xlim=c(min(pcX$x[,1])-100000, max(pcX$x[,1])+100000),ylim=c(min(pcX$x[,2])-100000, max(pcX$x[,2])+100000))
  text(pcX$x[,1],pcX$x[,2], labels, pos=3, cex=myCex)
  title(paste("Plot of first 2 PCs for expressions in", dataDesc, sep=" "), cex=0.8)
}

plotPCA(exprs(rawData), labels=sampleNames, dataDesc="raw data", colors=sampleColor,
        formapunts=c(rep(16,4),rep(17,4)), myCex=0.6)
```



#SAVE TO A FILE
```{r}


pdf(file.path(resultsDir, "QCPlots_Raw.pdf"))
boxplot(rawData, which="all",las=2, main="Intensity distribution of RAW data", 
        cex.axis=0.6, col=sampleColor, names=sampleNames)
plot(clust.euclid.average, labels=sampleNames, main="Hierarchical clustering of samples of RawData", 
     cex=0.7,  hang=-1)
plotPCA(exprs(rawData), labels=sampleNames, dataDesc="raw data", colors=sampleColor,
        formapunts=c(rep(16,4),rep(17,4)), myCex=0.6)
dev.off()
```






#---------------------------------------------------------------------------------------------
###DATA NORMALIZATION
#---------------------------------------------------------------------------------------------


```{r}
eset<-rma(rawData)

write.exprs(eset, file.path(resultsDir, "NormData.txt"))
```


#---------------------------------------------------------------------------------------------
###QUALITY CONTROL OF ARRAYS: NORMALIZED DATA
#---------------------------------------------------------------------------------------------


#BOXPLOT
```{r}

boxplot(eset, las=2, main="Intensity distribution of Normalized data", cex.axis=0.6, 
        col=sampleColor, names=sampleNames)

```

```{r}
#HIERARQUICAL CLUSTERING
clust.euclid.average <- hclust(dist(t(exprs(eset))),method="average")
plot(clust.euclid.average, labels=sampleNames, main="Hierarchical clustering of NormData", 
     cex=0.7,  hang=-1)

```


#PRINCIPAL COMPONENT ANALYSIS
```{r}
plotPCA <- function ( X, labels=NULL, colors=NULL, dataDesc="", scale=FALSE, formapunts=NULL, myCex=0.8,...)
{
  pcX<-prcomp(t(X), scale=scale) # o prcomp(t(X))
  loads<- round(pcX$sdev^2/sum(pcX$sdev^2)*100,1)
  xlab<-c(paste("PC1",loads[1],"%"))
  ylab<-c(paste("PC2",loads[2],"%"))
  if (is.null(colors)) colors=1
  plot(pcX$x[,1:2],xlab=xlab,ylab=ylab, col=colors, pch=formapunts, 
       xlim=c(min(pcX$x[,1])-10, max(pcX$x[,1])+10),ylim=c(min(pcX$x[,2])-10, max(pcX$x[,2])+10))
  text(pcX$x[,1],pcX$x[,2], labels, pos=3, cex=myCex)
  title(paste("Plot of first 2 PCs for expressions in", dataDesc, sep=" "), cex=0.8)
}

plotPCA(exprs(eset), labels=sampleNames, dataDesc="NormData", colors=sampleColor,
        formapunts=c(rep(16,4),rep(17,4)), myCex=0.6)

```



#SAVE TO A FILE
```{r}
pdf(file.path(resultsDir, "QCPlots_Norm.pdf"))
boxplot(eset, las=2, main="Intensity distribution of Normalized data", cex.axis=0.6, 
        col=sampleColor, names=sampleNames)
plot(clust.euclid.average, labels=sampleNames, main="Hierarchical clustering of NormData", 
     cex=0.7,  hang=-1)
plotPCA(exprs(eset), labels=sampleNames, dataDesc="selected samples", colors=sampleColor,
        formapunts=c(rep(16,4),rep(17,4)), myCex=0.6)
dev.off()
```


```{r eval=FALSE, include=FALSE}
install.packages("gridSVG")
source("http://bioconductor.org/biocLite.R")
biocLite('arrayQualityMetrics')

```

#ARRAY QUALITY METRICS
```{r}
arrayQualityMetrics(eset,  reporttitle="QualityControl", force=TRUE)
```



#---------------------------------------------------------------------------------------------
###FILTER OUT THE DATA
#---------------------------------------------------------------------------------------------

```{r}

annotation(eset) <- "org.Mm.eg.db"
eset_filtered <- nsFilter(eset, var.func=IQR,
                          var.cutoff=0.75, var.filter=TRUE,
                          filterByQuantile=TRUE)
#NUMBER OF GENES OUT
print(eset_filtered$filter.log$numLowVar)

#NUMBER OF GENES IN
print(eset_filtered$eset)


```


#---------------------------------------------------------------------------------------------
###DIFERENTIAL EXPRESSED GENES SELECTION. LINEAR MODELS. COMPARITIONS
#---------------------------------------------------------------------------------------------


```{r}

#CONTRAST MATRIX.lINEAR MODEL
treat <- targets$group
treat
lev <- factor(treat, levels = unique(treat))
lev
design <-model.matrix(~0+lev)
design
colnames(design) <- levels(lev)
rownames(design) <- as.vector(sampleNames)
print(design)

#COMPARISON
cont.matrix1 <- makeContrasts( 
  CD103.vs.CD14lo_cDCs = CD103-CD14lo_cDCs,
  CD103.vs.CD14hi_moDCs = CD103-CD14hi_moDCs,
  CD103.vs.inf.moDCs	= CD103-CD14hi_moDCs,
  
  CD14lo_cDCs.vs.CD14hi_moDCs = CD14lo_cDCs-CD14lo_cDCs,
  CD14lo_cDCs.vs.inf.moDCs = CD14lo_cDCs-CD14hi_moDCs,
  
  CD14hi_moDCs.vs.inf.moDCs = CD14hi_moDCs-inf.moDCs,
  
  levels = design)
comparison1 <- "Effect of Induction"

#MODEL FIT
fit1 <- lmFit(eset_filtered$eset, design)
fit.main1 <- contrasts.fit(fit1, cont.matrix1)
fit.main1 <- eBayes(fit.main1)


```




















